services:
  - type: web
    name: ukoo
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://ukoo.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ukoo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ukoo-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ukoo-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ukoo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ukoo-db
          property: password

databases:
  - name: ukoo-db
    databaseName: ukoo
    user: ukoo
    plan: free
